apiVersion: networking.gke.io/v1
kind: Network
metadata:
  name: control-network
spec:
  type: Device
  parametersRef:
    group: networking.gke.io
    kind: GKENetworkParamSet
    name: control-plane-params
